name: dango_fortune
description: "恋愛だんご占い"
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  crypto: ^3.0.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # ← 追加

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"     # ← 使いたいアイコンをここに置く

flutter:
  uses-material-design: true
  assets:
    - assets/config/diagnosis_config.json
    - assets/config/questions.json
    - assets/config/personality_main.json
    - assets/config/personality_sub.json
    - assets/config/personality_template.json
    - assets/config/fortune_daily.json
    - assets/dango/
    - assets/ui/
